main: com.mythicacraft.voteroulette.VoteRoulette
name: VoteRoulette
version: 0.3
author: ebiggz
description: A listener for Votifier
depends: [Votifier]
softdepends: [Vault]
commands:
    debugvote:
        description: debug vote
        usage: /<command>
    voteroulette:
        description: debug vote
        usage: /<command>
    vr:
        description: debug vote
        usage: /<command>