main: com.mythicacraft.voteroulette.VoteRoulette
name: VoteRoulette
version: 1.9.5
author: ebiggz
description: A listener for Votifier
softdepends: [Vault, Votifier]
commands:
    voteroulette:
        description: Access to VoteRoulette commands.
        usage: /<command> ?
        aliases: [vr, vtr]
    votelinks:
        description: Shows list of voting sites.
        usage: /<command>
        aliases: [vote, votesites]
permissions:
    voteroulette.viewstats:
        default: true
    voteroulette.viewrewards:
        default: true
    voteroulette.viewmilestones:
        default: true
    voteroulette.votecommand:
        default: true
    voteroulette.lastvote:
        default: true
    voteroulette.claimall:
        default: true
    voteroulette.viewotherstats:
        default: false
    voteroulette.editstats:
        default: false
    voteroulette.forcevote:
        default: false
    voteroulette.lastvoteothers:
        default: false
    voteroulette.remind:
        default: false
    voteroulette.admin:
        default: false
        children:
            voteroulette.viewotherstats: true
            voteroulette.editstats: true
            voteroulette.forcevote: true
            voteroulette.lastvoteothers: true
            voteroulette.remind: true
    voteroulette.*:
        default: op
        children:
            voteroulette.admin: true