#VotifierListener Config

##########
#Settings#
##########

# Set the following to true if you only want players to get rewarded after they vote so many times
# For example, you want them to vote on all your server lists before getting rewarded
# If this is false, players will receive an award every time they vote
giveRewardsOnThreshold: false

# If the above is set to true, this is the number of how many votes till a player will receive a reward
voteThreshold: 5

# Whether or not to send a message to a player when they vote
# You can customize this message in the localization.yml file
messagePlayer: true

# Whether or not to broadcast to the server when a player votes
# You can customize this message in the localization.yml file
broadcastToServer: false

#################
#Rewards Section#
#################

##Rewards List##
#
# Here you can make multiple rewards. 
# Each reward can have:
# - a list of items with quantities for each. 
# - an amount of money (if Vault is installed)
# - an amount of xp levels that will be given
# - a list of permission groups the reward will be considered for
# You can leave out any of these options if you do not wish to use them
#
#Example reward:
#    Awesome Reward: -- Name of the reward
#        items: 264(10), 276, 364(16) —- This one gives 10 diamonds, a diamond sword, and 16 steak 
#        currency: 100 —- $100 in-game currency (if vault is installed)
#        xpLevels: 5 —- Player will gain 5 xp levels
#        permGroups: Members, Donators —- Only players in the ‘Members’ or ‘Donators’ permission groups are eligible for the reward

Rewards:

    Default Reward:
        items: 264(1)

    #Lame Reward:
    #    items: 3(64)

# Set the following to true if you want a reward to be chosen at random (see rewards list below)
useRandomReward: false

# Use to set the default reward. (useRandomReward will override this if set to true)
defaultReward: ‘Default Reward’

#####################
#Blacklisted Players# 
#####################

# These players will not receive rewards
blacklistedPlayers:
    - Steve
    - Notch

# Set the following to true to switch the above blacklist to a whitelist, meaning only the players on that list will get rewards
useBlacklistAsWhitelist: false