#VoteRoulette Config

##########
#Settings#
##########

# Whether or not to send a message to a player when they vote
messagePlayer: true

# Whether or not to broadcast to the server when a player votes
broadcastToServer: true

# If broadcastToServer is set to true, should VoteRoulette only broadcast the votes from
# online players? (Helps cut down on spam on bigger servers)
onlyBroadcastOnlinePlayerVotes: false

# Whether or not to log to console when a player votes
logToConsole: true

# Whether or not to have the periodic reminder enabled
# You can change this reminder in the messages.yml file.
usePeriodicReminder: true

# How often the reminder is broadcasted (in minutes), if enabled.
periodicReminderInterval: 60

# Whether or not to have players notified when 24 hours has passed since their last vote
# You can change this reminder in the messages.yml file.
useTwentyFourHourReminder: true

# Whether or not to only consider a players primary group when doing permission group checks for rewards/milestones
# Turning this on helps with compatibility with GroupManager if you are using inheritance.
onlyConsiderPlayersPrimaryGroup: false

#################
#Rewards Section#
#################

##   Rewards List   ##
#
# Here you can make multiple rewards.
# Each reward can have:
# - a list of item IDs. Each item can have amount, dataID, enchants, name, and lore sections to further customize item!
# - an amount of money (if Vault is installed)
# - an amount of xp levels that will be given
# - worlds that players can claim the reward in
# - a list of commands to be run by the console. %player% will be replaced by the players name.
# - a list of permission groups the reward will be considered for (if Vault is installed)
# You can leave out any of these options if you do not wish to use them
# and you can use them in any order
#
# REMEMBER: Everything is indented 4 spaces from the next line and you can NOT use tabs
#
#Example reward:
#    Awesome Reward:                   # Name of the reward (Players will see this!)
#        items:                        # This one gives 5 diamonds, a diamond sword (with sharpness 5 enchant, 
#                                      # a custom name, and a lore message), 16 steak, and 32 green wool!
#            264:
#                amount: 5
#            276:
#                amount: 1
#                enchants: sharpness(5), looting(3)
#                name: Wrath of Herobrine
#                lore: A Mighty Sword 
#            364:
#                amount: 16
#            35: 
#                dataID: 5 
#                amount: 32
#            
#        currency: 100                 # Player will receive $100 in-game currency 
#        xpLevels: 5                   # Player will gain 5 xp levels
#        commands:
#            - gamemode %player% creative   # Players gamemode will be set to creative
#        permGroups: Members, Donators      # Only players in the Members or Donators permission groups are eligible for the reward
#        message: "&eCongrats %player%! You have received some awesome stuff and got creative mode!"    # This message will display to the player instead of the default one.
#                # Dont forget the quotes (" ") for the message section!
#        worlds: main_survival, temp_survival, creative_world

Rewards:
# Each reward must have a different name

    Ooh Shiny:
        items:
            264:
                amount: 1

#    Lame Reward:
#        items:
#            3:
#                amount: 64

# Set the following to true if you want a reward to be chosen at random
giveRandomReward: true

# Use to set the default reward.  (Only applies if giveRandomRewards is set to false)
defaultReward: Ooh Shiny

# Set the following to true if you only want players to get rewarded after they vote so many times
# For example, you want them to vote on all your server lists before getting rewarded
# If this is false, players will receive an award every time they vote
giveRewardsOnThreshold: false

# If the above is set to true, this is the number of how many votes till a player will receive a reward
voteThreshold: 5

# If you set any required worlds for a specific rewards, the following setting will make VoteRoulette consider the rewards that qualify for the world the player is currently standing in first. For example, if you had rewards set for a Survival world and a PvP world, and the player was in the Survival world when they voted, rewards that qualify for the Survival world will be considered first. If there is no rewards available for the current world, they will receive a reward as normal and will have to claim it in the correct world.

considerRewardsForPlayersCurrentWorld: true

##   Milestones List   ##
#
# Milestones are special rewards that are given after a player has made so many votes
# They are created in the config the same way as regular rewards, however you must include
# a "votes: #" section with how many votes you want the milestone to be! The milestone will otherwise
# be ignored. 
#
# You can also include a "recurring: true" section to have the milestone recur upon multiples
# For example, if the votes is set to 50 and recurring is true, players will receive this reward every 50 votes! (50, 100, 150, etc)
#
# If multiple milestones land on the same vote count, you can have one chosen at random (see below) or you can set which milestones have more priority over others using a
# "priority: #" section. It can be any number but 1 is considered highest priority (Think "first priority") and the number cant be less than 1. 
# If multiple milestones have the same priority levels, the first
# one will be used. The default priority is 10 if there is none specified.
#
#Example milestone:
#    Nickel and Dime:        # Name of the milestone (Players will see this!)
#        votes: 15           # The number of votes required to reach this milestone
#        currency: 200       # $200 in-game currency (if vault is installed)
#        xpLevels: 5         # Player will gain 5 xp levels
#        permGroups: VIP     # Only players in the VIP permission group are eligible for the milestone
#        recurring: false    # This milestone will open happen once, instead of every 15 votes!

Milestones:
# Each milestone must have a different name

#    My First Milestone:
#        votes: 25
#        recurring: true
#        currency: 100

# Set this to true to if you set multiple milestones with the same vote count and you want a random one to be chosen (if false, the one with the highest priority will be given!)    
giveRandomMilestone: false

# Set the following to false if you want players to get a regular reward on top of a milestone reward when they reach a milestone.
onlyRewardMilestoneUponCompletion: true

# If you set any required worlds for a specific milestones, the following setting will make VoteRoulette consider the milestones that qualify for the world the player is currently standing in first. For example, if you had milestones set for a Survival world and a PvP world, and the player was in the Survival world when they voted, only milestones that qualify for the Survival world will be considered first. If there is no milestones available for the current world, they will receive a milestone as normal and will have to claim it in the correct world.

considerMilestonesForPlayersCurrentWorld: false

#####################
#Blacklisted Players#
#####################

# These players will not receive rewards
blacklistedPlayers:
    - Steve
    - Herobrine

# Set the following to true to switch the above blacklist to a whitelist, meaning only the players on that list will get rewards
useBlacklistAsWhitelist: false

#####################
#Blacklisted Worlds#
#####################

# Players will not receive rewards/milestones in these worlds, ever!
blacklistedWorlds:
    - A_World
    - Another_World

# End of config
#####################
# No need to touch this
configVersion: 1.3