main: com.mythicacraft.voteroulette.VoteRoulette
name: VoteRoulette
version: 1.3
author: ebiggz
description: A listener for Votifier
softdepends: [Vault, Votifier]
commands:
    voteroulette:
        description: Access to VoteRoulette commands.
        usage: /<command> ?
    vr:
        description: Access to VoteRoulette commands.
        usage: /<command> ?
    vote:
        description: Shows list of voting sites.
        usage: /<command>
permissions:
    voteroulette.viewstats:
        default: true
    voteroulette.viewrewards:
        default: true
    voteroulette.viewmilestones:
        default: true
    voteroulette.votecommand:
        default: true
    voteroulette.viewotherstats:
        default: false
    voteroulette.editstats:
        default: false
    voteroulette.forcevote:
        default: false    
    voteroulette.admin:
        default: false
        children:
            voteroulette.viewotherstats: true
            voteroulette.editstats: true
            voteroulette.forcevote: true
    voteroulette.*:
        default: op
        children:
            voteroulette.admin: true